apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop 
  labels:
    purpose: multi-container
spec:
  containers:
  - name: nginx
    image: nginx #container 1 in this manifest yaml-file
  - name: almalinux
    image: almalinux:9 #AlmaLinux is a base OS image and It has no default foreground process
    command: ["sleep", "1000"]