apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: roboshop
    component: frontend
    environment: dev     #selectors for configuring endpoints in services to pod to pod
  ports:
    - protocol: TCP
      port: 80        # Service port exposed outside the cluster
      targetPort: 80  # Container port like cataloue 1  ,2 or 3 #here conatiner is nginx(80/443)
      
#serive means
#kind is "service"
#under "spec"
#selecter and Ports 
#under ports(list)
#- protocol:TCP
#port:80 "service prot"
#targetport:80 "conatiner-port"