apiVersion: v1
kind: Pod
metadata:
  name: crash-pod
spec:
  containers:
  - name: crash-container
    image: nginx
        #command: ["/bin/sh", "-c", "exit 1"]
    command: ["/bin/sh", "-c", "sleep 3600"]